from typing import List, TypedDict, Optional, Dict, Any
from io import BytesIO

class DocumentData(TypedDict):
    filename: str
    text: str

class SectionData(TypedDict):
    section_title: str
    content: str

class GraphState(TypedDict):
    """
       Represents the state of our graph.

       Attributes:
           rfp_file: Extracted RFP file
           rfp_name: Extracted RFP name
           template_file: Extracted Template file
           template_name: Extracted Template name
           additional_files: Optional uploaded docs
           rfp_text: Extracted RFP text
           template_text: Extracted Template text
           additional_docs: Optional uploaded docs
           user_instructions: User instructions
           proposal_outline: JSON structure generated by LLM
           structure_feedback: User feedback on structure
           structure_approved: Whether structure is approved
           current_section: Section currently being generated/reviewed
           concatenated_sections: All approved/generated sections so far
           section_feedback: User feedback on current section
           section_approved: Whether section is approved
           sections_to_delete: Sections to delete
           new_section_order: New section order
           exported_document: Exported document
           current_step: Current node/stage name
           continue_generation: Whether LLM should continue or finish
       """
    # === Input Stage ===
    rfp_file: Optional[BytesIO]
    rfp_name: Optional[str]
    template_file: Optional[BytesIO]
    template_name: Optional[str]
    additional_files: Optional[List[Dict[str, Any]]]
    rfp_text: str
    template_text: str
    additional_docs: List[DocumentData]
    user_instructions: Optional[str]

    # === Structure Stage ===
    proposal_outline: Optional[Dict[str, Any]]
    structure_feedback: Optional[str]
    structure_approved: bool

    # === Section Stage ===
    current_section: Optional[SectionData]
    concatenated_sections: List[SectionData]
    section_feedback: Optional[str]
    section_approved: bool

    # === Reorder/Delete Stage ===
    sections_to_delete: Optional[List[int]]
    new_section_order: Optional[List[int]]

    # === Export Stage ===
    exported_document: Optional[BytesIO]

    # === Control Flags ===
    current_step: str
    continue_generation: bool
